#!/usr/bin/env bash
# installing nginx web server and writing hello world
sudo apt -y update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
