#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# In the 9th iteration, It will display "Hi" before "Best School".

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
        echo "Best School"
    (( i++ ))
done
